### ISSUE TITLE
Use strlen to fetch string length

### ISSUE THREAD

**Issue by j0ng4b** [aCube1/Chip8#15]
Only do `memcpy` until `strlen` of args[] do this check what is smaller the `strlen` result or `MAX_FILEPATH_SIZE`:
https://github.com/aCube1/Chip8/blob/f2a0169ff76daf5ad3082d67f3f5c3b40d0e9e77/src/configs.c#L102

Instead of use MAX_FILEPATH_SIZE a better approach would be use `strlen` to set the string termination (`\0`) at the end of `config->rom_filepath`:
https://github.com/aCube1/Chip8/blob/f2a0169ff76daf5ad3082d67f3f5c3b40d0e9e77/src/configs.c#L103
Because the `strlen` will return the real string length make the termination really meaningful.

**Comment by acubeone** [comment]
Check the c7e8df3 commit.
